---
apiVersion: v1
kind: Service
metadata:
  name: user-service-expose
  namespace: default
  labels:
    app: user-service
spec:
  ports:
  - name: user-service
    protocol: TCP
    port: 31704
    targetPort: 8181
    nodePort: 31704
  selector:
    app: user-service
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  ports:
  - port: 8181
    targetPort: 8181
    name: user-service
  clusterIP: None
  selector:
    app: user-service
---    
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: user-service
spec:
  serviceName: "user-service"
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - resources:
          requests:
            cpu: 100m
            memory: 192Mi 
        name: user-eureka
        image: mycluster.icp:8500/default/kbastani/user-service:latest
        ports:
        - containerPort: 8181
        env:
        - name: JAVA_OPTS
          value: |
            -Xmx160m
              -Deureka.client.serviceUrl.defaultZone=http://microservice-eureka-0.microservice-eureka.default.svc.cluster.local:8761/eureka/,http://microservice-eureka-1.microservice-eureka.default.svc.cluster.local:8761/eureka/,http://microservice-eureka-2.microservice-eureka.default.svc.cluster.local:8761/eureka/
        - name: spring.profiles.active
          value: "cloud"
        - name: spring.cloud.config.uri
          value: "http://config-service.default.svc.cluster.local:8888"
  podManagementPolicy: "Parallel"
